web/config/routes.rb
Rails.application.routes.draw do
  resources :orders, :only => [:index, :create]
  resources :items, :except => [:new]
  root 'home#index'
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    # TODO: Change this to session[:app_session_id]
    if $session_id
      @_current_user ||= DoubleDog.db.get_user_by_session_id($session_id)
    end
  end

  helper_method :current_user
end

web/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
    team_id = params[:team].to_i
    team_name = params[:team_name]
    tags = params[:tags].split(',').collect {|t| t.strip}
    user_name = params[:user]
    event_name = params[:event_name]

    result = Timeline::CreateEvent.run name: event_name, team_id: team_id, tags: tags, user_name: user_name
    if result.success?
      redirect_to({action: 'show', controller: 'teams', team_id: team_id, team_name: team_name}, alert: "Event successfully added.")
    else
      redirect_to({action: 'show', controller: 'teams', team_id: team_id, team_name: team_name}, alert: "Error: " + result.error.to_s)
    end    
  end
end

web/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

web/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = DoubleDog.db.all_items
  end

  def create
    tx_params = item_params.merge :session_id => $session_id
    tx_params[:price] = tx_params[:price].to_f
    result = DoubleDog::CreateItem.new.run(tx_params)

    if result[:success?]
      redirect_to item_path(result[:item].id)
    else
      @items = DoubleDog.db.all_items
      @item = DoubleDog::Item.new(nil, tx_params[:name], tx_params[:price])
      @error = result[:error]
      render 'index'
    end
  end

  def show
    @item = DoubleDog.db.get_item  params[:id].to_i
  end

  def edit
    @item = DoubleDog.db.get_item  params[:id].to_i
  end

  def update
    # DoubleDog::UpdateItem would go here
  end

  def destroy
    # DoubleDog::DestroyItem would go here
  end

  private

  def item_params
    params.require(:item).permit(:name, :price)
  end

  def authenticate_admin!
    if current_user.nil? || !current_user.admin?
      redirect_to root_path
      return false
    end
  end
end

web/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = DoubleDog.db.all_orders
  end

  def create
  end
end

web/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    result = Timeline::GetTeams.run
    if result.success?
      @teams = result.teams
      render 
    else
      @teams = []
      render alert: "Error accessing teams."
    end    
  end

  def show
    @team_id = params[:team_id].to_i
    @team_name = params[:team_name]
    result = Timeline::GetTeamEvents.run :team_id => @team_id
    if result.success?
      @events = result.events
      render    
    else
      return redirect_to({:action => :index}, alert: "Error accessing team events.") unless @events
    end
  end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/events_helper.rb
module EventsHelper
end

web/app/helpers/home_helper.rb
module HomeHelper
end

web/app/helpers/items_helper.rb
module ItemsHelper
end

web/app/helpers/orders_helper.rb
module OrdersHelper
end

web/app/helpers/teams_helper.rb
module TeamsHelper
end

web/app/views/events/create.html.erb
<h1>Events#create</h1>
<p><%= @error %></p>

web/app/views/events/new.html.erb
<h1>Events#new</h1>

web/app/views/home/index.html.erb
<h1>Welcome to Double Dog PoS</h1>

<% if current_user %>
  <p>Welcome, <%= current_user.username %>!</p>
<% end %>

<% if current_user && current_user.admin? %>
  <p><%= link_to "Visit items dashboard", items_path %></p>
<% end %>

web/app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

web/app/views/items/edit.html.erb
<h1>Editing: <%= @item.name %></h1>

<%= form_tag item_path(@item.id), :method => :put do %>

  <%= label_tag 'item[name]', 'Item Name:' %>
  <%= text_field_tag 'item[name]', @item.name %>
  <br />

  <%= label_tag 'item[price]', 'Item Price:' %>
  <%= text_field_tag 'item[price]', @item.price %>
  <br />

  <%= submit_tag 'Update Item' %>
<% end %>

web/app/views/items/index.html.erb
<h1>Items Dashboard</h1>

<h2>New Item</h2>
<% if @error %>
  <p>Error: <%= @error %></p>
<% end %>
<%= form_tag items_path, :method => :post do %>

  <%= label_tag 'item[name]', 'Item Name:' %>
  <%= text_field_tag 'item[name]' %>
  <br />

  <%= label_tag 'item[price]', 'Item Price:' %>
  <%= text_field_tag 'item[price]' %>
  <br />

  <%= submit_tag 'Create Item' %>
<% end %>

<h2>All Items</h2>
<% @items.each do |item| %>
<p>
  <%= link_to item.name, item_path(item.id) %> $<%= item.price %>
</p>
<% end %>

web/app/views/items/show.html.erb
<%= link_to "<-- Back to all items", items_path %>
<h1><%= @item.name %></h1>
<p>Price: $<%= @item.price %></p>

<%= link_to "Edit item", edit_item_path(@item.id) %>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

web/app/views/orders/index.html.erb
<h2>All Orders</h2>

<% @orders.each do |order| %>
<p>
  Order #<%= order.id %>
  <ul>
    <% order.items.each do |item| %>
      <li><%= item.name %></li>
    <% end %>
  </ul>
</p>
<% end %>